name: Docker Image CI

on:
  push:
    tags:        
      - 'v*.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build ./nomodel --file Dockerfile --tag docker.io/pllin/cv-nomodel:${{  github.ref_name }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
       image-ref: 'docker.io/pllin/cv-nomodel:${{  github.ref_name }}'
       format: 'table'
       exit-code: '1'
       ignore-unfixed: true
       vuln-type: 'os,library'
       severity: 'CRITICAL,HIGH'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: docker.io/pllin/cv-nomodel:${{  github.ref_name }}
